
[tasks.generate-sheet]
description = "Generate sheet music from base.ly using LilyPond in a Docker container."
alias = ["gs"]

usage = '''
flag "--file <file>" help="LilyPond file to process"
'''

run =''' 
    docker run --rm -v "$(pwd):/app" -w /app lilypond-jp lilypond ${usage_file}
    mv *.pdf sheet-music
'''

[tasks.build-image]
description = "Build the Docker image for LilyPond."
alias = ["bi"]
run = ['docker build -t lilypond-jp .']


[tools]
usage = "latest"
watchexec = "latest"
